repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args:
          - --maxkb=2048
        exclude: ^test/fixture.json|^test/dump.sql/db.sqlite3
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        exclude: ^manage.py|migrations/|demo/|urls.py
      - id: flake8
        exclude: ^manage.py|migrations/|demo/|urls.py
      - id: name-tests-test
        args:
          - --django
        exclude: ^tests/testapp|^tests/management/|^tests/collisions/|^tests/pythonrc.py
