# Generated by Django 4.1.5 on 2023-01-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junkyard_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
