# Generated by Django 4.1.5 on 2023-01-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junkyard_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
